name: Renovate

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          owner: ${{ github.repository_owner }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.13
        with:
          configurationFile: renovate.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.event.inputs.repositories || secrets.RENOVATE_REPOSITORIES }}
          LOG_LEVEL: debug
       env:
          RENOVATE_REPOSITORIES: ${{ secrets.RENOVATE_REPOSITORIES }}
          LOG_LEVEL: debug
